# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MidSwiftSample1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MidtransKit', '1.18.0'

end
